import React,{useState} from 'react';
import { api } from '../services/apiService';
import { AIInterpretationResult } from '../services/aiService';
interface Props{onApply:(r:AIInterpretationResult)=>void}
export const ImageDoctorFinder:React.FC<Props>=({onApply})=>{
 const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(false); const [result,setResult]=useState<any>(null);
 const analyze=async()=>{if(!file)return;setLoading(true);setResult(null);try{const r=await api.analyzeImage(file);setResult(r);if(r.suggestedSpecialty)onApply({specialty:r.suggestedSpecialty,gender:'No Preference',date:'Tomorrow',time:'Anytime',location:'All local facilities',rawSymptoms:r.concern||'Image input',language:'English',explanation:r.explanation||r.message||'Suggested a specialty for care navigation.',matchedKeywords:r.concern?[r.concern]:[]});}catch(e){setResult({message:'Image analysis failed. Please try another image.'});}finally{setLoading(false)}};
 return <div className="bg-white p-6 rounded-3xl border border-slate-200"><div className="flex items-start gap-4"><div className="w-12 h-12 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><i className="fa-solid fa-camera text-xl"/></div><div className="flex-1"><h3 className="text-base font-bold text-slate-900">Upload a picture to find the right doctor</h3><p className="text-sm text-slate-500 mt-1">Skin photos, visible eye/ear/throat concerns, dental photos, injury images and other healthcare images can be submitted for navigation. This is not a diagnosis.</p><input className="mt-4 block w-full text-sm" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||loading} onClick={analyze} className="mt-4 px-5 py-2.5 rounded-xl bg-indigo-600 text-white font-semibold text-sm disabled:bg-slate-300">{loading?'Analyzing image...':'Analyze & Suggest Doctor'}</button>{result&&<div className="mt-4 p-4 rounded-2xl bg-slate-50 border border-slate-200 text-sm"><b>{result.concern||'Image received'}</b><p className="text-slate-600 mt-1">{result.explanation||result.message}</p>{result.suggestedSpecialty&&<p className="mt-2 font-semibold text-teal-700">Suggested specialty: {result.suggestedSpecialty}</p>}</div>}</div></div></div>
}

